export { default as EditProfileHero } from './EditProfileHero';
export { default as EditPersonalInformation } from './EditPersonalInformation';
export { default as EditEducation } from './EditEducation';
export { default as EditProfessionalInfo } from './EditProfessionalInfo';
export { default as EditCertifications } from './EditCertifications';
export { default as EditSocialLinks } from './EditSocialLinks';
export { default as EditLearningPreferences } from './EditLearningPreferences';
export { default as EditPrivacySettings } from './EditPrivacySettings';
export { TwoFactorSettings } from './TwoFactorSettings';
export { ActiveSessionsSection } from './ActiveSessionsSection';
export { SecureEmailVerificationSection } from './SecureEmailVerificationSection';
export { ChangePasswordSection } from './ChangePasswordSection';
export { LoginHistorySection } from './LoginHistorySection';
export { DangerZoneSection } from './DangerZoneSection';
